version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./schema.yml:/schema.yml
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SWAGGER_JSON=/schema.yml
    restart: always     # or "unless-stopped"
