openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /search/:
    get:
      operationId: search_list
      tags:
      - search
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
          description: ''
components:
  schemas:
    Employee:
      type: object
      properties:
        first_name:
          type: string
          maxLength: 200
        last_name:
          type: string
          maxLength: 200
        contact_info:
          type: string
          maxLength: 200
        department:
          type: string
          maxLength: 200
        position:
          $ref: '#/components/schemas/PositionEnum'
        location:
          $ref: '#/components/schemas/LocationEnum'
        status:
          $ref: '#/components/schemas/StatusEnum'
      required:
      - contact_info
      - department
      - first_name
      - last_name
      - location
      - position
      - status
    LocationEnum:
      enum:
      - HO_CHI_MINH
      - SINGAPORE
      - NO_LOCATION
      type: string
      description: |-
        * `HO_CHI_MINH` - Ho Chi Minh
        * `SINGAPORE` - Singapore
        * `NO_LOCATION` - No Location
    PositionEnum:
      enum:
      - ASSISTANT_MANAGER
      - DIRECTOR
      - OTHER
      - INTERN
      - EMPLOYEE
      - VICE_PRESIDENT
      type: string
      description: |-
        * `ASSISTANT_MANAGER` - ASSISTANT_MANAGER
        * `DIRECTOR` - DIRECTOR
        * `OTHER` - OTHER
        * `INTERN` - INTERN
        * `EMPLOYEE` - EMPLOYEE
        * `VICE_PRESIDENT` - VICE_PRESIDENT
    StatusEnum:
      enum:
      - ACTIVE
      - NOT_STARTED
      - TERMINATED
      type: string
      description: |-
        * `ACTIVE` - ACTIVE
        * `NOT_STARTED` - NOT_STARTED
        * `TERMINATED` - TERMINATED
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
